### ISSUE TITLE
Arg checks for calcSpeeds

### ISSUE THREAD

**Issue by kaijagahm** [kaijagahm/vultureUtils#118]
When Elvira tried to use calcSpeeds outside the context of another function, she accidentally fed it data where the latitude and longitude columns weren't numeric, and it failed in an unclear way. Should add checks to make sure the columns indicated by the `latCol` and `longCol` parameters are numeric, even though that will probably be extraneous in most cases.

**Comment by ryannguyen6392** [comment]
Got fixed in one of the commits, but I can't find it.
